// Generated by CoffeeScript 1.9.2
(function() {
  var coffee, fs, gulp, istanbul, mocha;

  gulp = require('gulp');

  coffee = require('gulp-coffee');

  mocha = require('gulp-mocha');

  istanbul = require('gulp-istanbul');

  fs = require('fs-extra');

  gulp.task('compile_coffee', function() {
    return gulp.src(['**/*.coffee', 'index.coffee', '!node_modules/**/*.coffee']).pipe(coffee()).pipe(gulp.dest('build/'));
  });

  gulp.task('test', ['compile_coffee'], function(cb) {
    var test;
    test = function() {
      return gulp.src(['build/lib/**/*.js', 'build/index.js']).pipe(istanbul()).pipe(istanbul.hookRequire()).on('finish', function() {
        return gulp.src(['build/test/*.js']).pipe(mocha()).pipe(istanbul.writeReports()).on('end', function() {
          cb();
          return process.exit(0);
        });
      });
    };
    return process.nextTick(test);
  });

  gulp.task('default', ['compile_coffee'], function() {
    fs.copySync('./test/rss_test', './build/test/rss_test');
    return gulp.start('test');
  });

}).call(this);
